### ISSUE TITLE
Timeout when trying to configure addon

### ISSUE THREAD

**Issue by false-vacuum** [doingodswork/deflix-stremio#10]
For the past few days anytime I try reconfiguring the addon I'm getting a 502. Seems a few people on Reddit are reporting the same thing:

https://www.reddit.com/r/StremioAddons/comments/oawaaq/deflix_configuration_timing_out/

**Comment by infekSK** [comment]
Can also confirm, no luck configuring, eventually times out.

**Comment by doingodswork** [comment]
Thanks for reporting the issue! I was offline for the past two weeks and unfortunately one of the servers where the Deflix addon is running had a problem. I just removed it from Cloudflare DNS so requests should now route to the healthy servers only. Sorry for the inconvenience, I'll try to improve the infrastructure to automatically mitigate such issues in the future. I'll also engage with the Reddit and Discord community in the next days to explain the downtime.

**Comment by false-vacuum** [comment]
Thank you for the response! Really love the app you have here.

**Comment by infekSK** [comment]
Thanks for the fix!
